export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_USER_DATA = "GET_USER_DATA";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";
//Report

export const GET_LAST_TRANSACTION = "GET_LAST_TRANSACTION";

//Companies Types
//jawwal
export const GET_JAWWAL_3G = "GET_JAWWAL_3G";
export const GET_JAWWAL_CREDIT = "GET_JAWWAL_CREDIT";
export const GET_JAWWAL_MIN = "GET_JAWWAL_MIN";
export const GET_JAWWAL_ROM = "GET_JAWWAL_ROM";
export const GET_JAWWAL_CHARGE = "GET_JAWWAL_CHARGE";
export const ADD_JAWWAL_CHARGE = "ADD_JAWWAL_CHARGE";
export const GET_RENEW_JAWWAL_MIN = "GET_RENEW_JAWWAL_MIN";
export const GET_NOT_RENEW_JAWWAL_MIN = "GET_NOT_RENEW_JAWWAL_MIN";
export const GET_RENEW_JAWWAL_3G = "GET_RENEW_JAWWAL_3G";
export const GET_NOT_RENEW_JAWWAL_3G = "GET_NOT_RENEW_JAWWAL_3G";
export const LOADING_TRUE = "LOADING_TRUE";

//Ooredoo
export const GET_OOREDOO_3G = "GET_OOREDOO_3G";
export const GET_OOREDOO_RENEW_3G = "GET_OOREDOO_RENEW_3G";
export const GET_OOREDOO_NOT_RENEW_3G = "GET_OOREDOO_NOT_RENEW_3G";
export const GET_OOREDOO_MIN = "GET_OOREDOO_MIN";
export const GET_OOREDOO_RENEW_MIN = "GET_OOREDOO_RENEW_MIN";
export const GET_OOREDOO_NOT_RENEW_MIN = "GET_OOREDOO_NOT_RENEW_MIN";
export const GET_OOREDOO_ROM = "GET_OOREDOO_ROM";
export const GET_OOREDOO_RENEW_ROM = "GET_OOREDOO_RENEW_ROM";
export const GET_OOREDOO_NOT_RENEW_ROM = "GET_OOREDOO_NOT_RENEW_ROM";
export const GET_OOREDOO_SUPER = "GET_OOREDOO_SUPER";
export const GET_RENEW_OOREDOO_SUPER = "GET_RENEW_OOREDOO_SUPER";
export const GET_NOR_RENEW_OOREDOO_SUPER = "GET_NOR_RENEW_OOREDOO_SUPER";

//Group Companies

export const GET_GROUP_COMPANIES = "GET_GROUP_COMPANIES";

// hot and azy Company
export const GET_AZY = "GET_AZY";
export const GET_HOT = "GET_HOT";

//Cards
export const GET_CARDS = "GET_CARDS";
export const GET_COPMANY_CARDS = "GET_COPMANY_CARDS ";
